AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example of processing messages on an SQS queue with Lambda
Resources:
  MySQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.localstacklambda.SQSFunctionHandler
      FunctionName: event-printer
      Runtime: java11
      Timeout: 180
      MemorySize: 1024
      CodeUri: s3://bucket1
      Environment:
        Variables:
          MAIN_CLASS: com.example.localstacklambda.LambdaLocalstackApplication
